### ISSUE TITLE
JOSS submission

### ISSUE THREAD

**Issue by dirmeier** [osorensen/hdme#26]
Dear Øystein,
I have only very minor revisions for the manuscript itself. I uploaded the PDF with corrections [here](https://www.dropbox.com/s/6d75kdnhimuatgz/10.21105.joss.01404-SD.pdf?dl=0#)

Some other things:
- In your [paper from 2018](https://doi.org/10.1080/10618600.2018.1425626) I believe you describe the GMUS and GMUL already. Correct me if I am wrong, but does that mean you already published the code of these (and their non-generalized Gaussian cases) as code?
- I think it would make sense to cite some at least remotely similar packages like [this](https://cran.r-project.org/web/packages/GLSME/).

Best,
S

**Comment by osorensen** [comment]
Dear Simon

Regarding your first point:

Thanks a lot for you comment on the manuscript. Yes, code for running the experiments with GMUS and GMUL were included as supplementary material in the [2018 paper](https://www.tandfonline.com/doi/full/10.1080/10618600.2018.1425626). This supplementary material was not subject to peer review, and when submitting the hdme package to JOSS I considered that paper as a purely methodological paper. The paper also states that code is available in this GitHub repository, but that refers to a much older version of this package, which was not on CRAN.

However, I realize now that this means part of the code in this package is actually part of the supplementary material of an already published paper, and that I should have made you aware of this. That being said, the package currently submitted has much more functionality and methods implemented, documentation and vignette, so much work has been done since then.

**Comment by dirmeier** [comment]
Right, I was just trying to point out if there could be licensing issues with the Journal of Computational and Graphical Statistics. 

Other than that I have no comments about the manuscript.  For the code, as Doug Bates pointed out methods like `coef`, `summary`, etc. would be nice to have. The rest of the package/documentation/code is great!

**Comment by osorensen** [comment]
Ok, thanks a lot!

**Comment by osorensen** [comment]
Thanks for the clarification, Simon. And thanks for your pdf with corrections. I will work through them now and update the paper.

**Comment by osorensen** [comment]
A comment on the formatting of references: I have capitalized titles properly in paper.bib, but let the JOSS compiler (i.e., "whedon") decide how the final formatting becomes. This appears to be the recommended way of doing it.

**Comment by dirmeier** [comment]
Okay, I wasn't aware. Should be fine then. I'll close this then.
